services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - ../config/.Development.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin
    env_file:
      - ../config/.Development.env
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  java-server:
    container_name: java-server
    image: java-server:latest
    env_file:
      - ../config/.Development.env
    build:
      context: ..
      dockerfile: docker/dockerfiles/Development.Server.Dockerfile
    ports:
      - "7777:7777"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  flyway:
    image: flyway/flyway:9
    command: -url=jdbc:postgresql://postgres:5432/flashcards_db -user=postgres -password=9tcXCjJ3Xb4rDQhy9sfVGKyv migrate
    volumes:
      - ../src/application/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
    networks:
      - app-network

networks:
   app-network:
    driver: bridge